Repository dsanchezchu/megalabs-api, pull requests merged in 2024-11, with the labels that each got.

#46 feat(develop): Merge con el develop
  src/main/resources/application.properties
Labels: sprint 2, Backend

#45 Historias alexander 22-23
  src/main/java/com/megalabsapi/api/DetalleVentaController.java
  src/main/java/com/megalabsapi/api/EncuestaEntregaController.java
  src/main/java/com/megalabsapi/api/EncuestaRecojoController.java
  src/main/java/com/megalabsapi/api/MedicamentoController.java
  src/main/java/com/megalabsapi/model/entity/EncuestaEntrega.java
  src/main/java/com/megalabsapi/model/entity/EncuestaRecojo.java
  src/main/java/com/megalabsapi/repository/EncuestaEntregaRepository.java
  src/main/java/com/megalabsapi/repository/EncuestaRecojoRepository.java
  src/main/java/com/megalabsapi/service/DetalleVentaService.java
  src/main/java/com/megalabsapi/service/EncuestaEntregaService.java
  src/main/java/com/megalabsapi/service/EncuestaRecojoService.java
  src/main/java/com/megalabsapi/service/MedicamentoService.java
  src/main/resources/application.properties
Labels: sprint 2, Backend

#47 Feature/sprint3 leonardo
  src/main/java/com/megalabsapi/api/CalendarioController.java
  src/main/java/com/megalabsapi/api/ControlCalidadController.java
  src/main/java/com/megalabsapi/api/EntregaMuestraController.java
  src/main/java/com/megalabsapi/config/WebSecurityConfig.java
  src/main/java/com/megalabsapi/dto/EntregaMuestraDTO.java
  src/main/java/com/megalabsapi/dto/EntrevistaDTO.java
  src/main/java/com/megalabsapi/dto/EstudioClinicoDTO.java
  src/main/java/com/megalabsapi/repository/DetalleVentaRepository.java
  src/main/java/com/megalabsapi/repository/EntrevistaRepository.java
  src/main/java/com/megalabsapi/repository/MedicamentoRepository.java
  src/main/java/com/megalabsapi/service/ControlCalidadService.java
  src/main/java/com/megalabsapi/service/EntregaMuestraService.java
  src/main/java/com/megalabsapi/service/EntrevistaService.java
  src/main/java/com/megalabsapi/service/impl/ControlCalidadServiceImpl.java
  src/main/java/com/megalabsapi/service/impl/EntregaMuestraServiceImpl.java
  src/main/java/com/megalabsapi/service/impl/EntrevistaServiceImpl.java
  src/main/resources/application.properties
Labels: sprint 3, Backend

#50 Feature/sprint3 part2
  src/main/java/com/megalabsapi/api/AuditoriaController.java
  src/main/java/com/megalabsapi/api/CatalogoController.java
  src/main/java/com/megalabsapi/api/ProductoController.java
  src/main/java/com/megalabsapi/api/ProgramacionRecojoController.java
  src/main/java/com/megalabsapi/config/WebSecurityConfig.java
  src/main/java/com/megalabsapi/dto/AuditoriaDTO.java
  src/main/java/com/megalabsapi/dto/ProgramacionRecojoDTO.java
  src/main/java/com/megalabsapi/model/entity/Auditoria.java
  src/main/java/com/megalabsapi/model/entity/Cliente.java
  src/main/java/com/megalabsapi/model/entity/ProgramacionRecojo.java
  src/main/java/com/megalabsapi/repository/AuditoriaRepository.java
  src/main/java/com/megalabsapi/repository/ProgramacionRecojoRepository.java
  src/main/java/com/megalabsapi/service/AuditoriaService.java
  src/main/java/com/megalabsapi/service/CatalogoService.java
  src/main/java/com/megalabsapi/service/ProductoService.java
  src/main/java/com/megalabsapi/service/ProgramacionRecojoService.java
  src/main/java/com/megalabsapi/service/impl/AuditoriaServiceImpl.java
  src/main/java/com/megalabsapi/service/impl/CatalogoServiceImpl.java
  src/main/java/com/megalabsapi/service/impl/ProductoServiceImpl.java
  src/main/java/com/megalabsapi/service/impl/ProgramacionRecojoServiceImpl.java
  src/main/resources/application.properties
Labels: Backend

#51 Historias 24-27-28-29
  src/main/java/com/megalabsapi/api/CitaController.java
  src/main/java/com/megalabsapi/api/InsatisfaccionProductoController.java
  src/main/java/com/megalabsapi/api/OrdenCompraController.java
  src/main/java/com/megalabsapi/api/RegulacionController.java
  src/main/java/com/megalabsapi/config/WebSecurityConfig.java
  src/main/java/com/megalabsapi/dto/OrdenCompraDTO.java
  src/main/java/com/megalabsapi/model/entity/Cita.java
  src/main/java/com/megalabsapi/model/entity/InsatisfaccionProducto.java
  src/main/java/com/megalabsapi/model/entity/OrdenCompra.java
  src/main/java/com/megalabsapi/model/entity/Proveedor.java
  src/main/java/com/megalabsapi/model/enums/TipoQueja.java
  src/main/java/com/megalabsapi/repository/CitaRepository.java
  src/main/java/com/megalabsapi/repository/InsatisfaccionProductoRepository.java
  src/main/java/com/megalabsapi/repository/OrdenCompraRepository.java
  src/main/java/com/megalabsapi/repository/ProveedorRepository.java
  src/main/java/com/megalabsapi/repository/RegulacionRepository.java
  src/main/java/com/megalabsapi/service/CitaService.java
  src/main/java/com/megalabsapi/service/InsatisfaccionProductoService.java
  src/main/java/com/megalabsapi/service/OrdenCompraService.java
  src/main/java/com/megalabsapi/service/RegulacionService.java
  src/main/java/com/megalabsapi/service/impl/InsatisfaccionProductoServiceImpl.java
  src/main/resources/application.properties
Labels: Backend

#52 Feature/envio correo con templates
  pom.xml
  src/main/java/com/megalabsapi/api/DetalleVentaController.java
  src/main/java/com/megalabsapi/integration/notification/email/dto/Mail.java
  src/main/java/com/megalabsapi/integration/notification/email/service/EmailService.java
  src/main/java/com/megalabsapi/model/entity/Cliente.java
  src/main/java/com/megalabsapi/service/DetalleVentaService.java
  src/main/java/com/megalabsapi/service/impl/DetalleVentaServiceImpl.java
  src/main/java/com/megalabsapi/service/impl/EntregaMuestraServiceImpl.java
  src/main/resources/application.yml
  src/main/resources/data-test.sql
  src/main/resources/templates/confirmation.html
  src/main/resources/templates/password-reset-templates.html
Labels: Backend

#58 feat(fix): Funcionalidades de Entrega-Muestra corregidas
  src/main/java/com/megalabsapi/api/EntregaMuestraController.java
  src/main/java/com/megalabsapi/dto/EntregaMuestraDTO.java
  src/main/java/com/megalabsapi/model/entity/Entrega_Muestra.java
  src/main/java/com/megalabsapi/service/EntregaMuestraService.java
  src/main/java/com/megalabsapi/service/impl/EntregaMuestraServiceImpl.java
Labels: fix

#62 Improved - Se mejoro el controller de citas asi como su service
  src/main/java/com/megalabsapi/api/CitaController.java
  src/main/java/com/megalabsapi/dto/CitaDTO.java
  src/main/java/com/megalabsapi/dto/CitaRequestDTO.java
  src/main/java/com/megalabsapi/model/entity/Cita.java
  src/main/java/com/megalabsapi/model/entity/Representante.java
  src/main/java/com/megalabsapi/model/enums/CitaMotivo.java
  src/main/java/com/megalabsapi/model/enums/EstadoCita.java
  src/main/java/com/megalabsapi/repository/CitaRepository.java
  src/main/java/com/megalabsapi/repository/ClienteRepository.java
  src/main/java/com/megalabsapi/service/CitaService.java
  src/main/resources/data-test.sql
Labels: Backend

#63 Develop : Despliegue - Jeffry - v 0.1.4
  src/main/java/com/megalabsapi/api/CitaController.java
  src/main/java/com/megalabsapi/dto/CitaDTO.java
  src/main/java/com/megalabsapi/dto/CitaRequestDTO.java
  src/main/java/com/megalabsapi/model/entity/Cita.java
  src/main/java/com/megalabsapi/model/entity/Representante.java
  src/main/java/com/megalabsapi/model/enums/CitaMotivo.java
  src/main/java/com/megalabsapi/model/enums/EstadoCita.java
  src/main/java/com/megalabsapi/repository/CitaRepository.java
  src/main/java/com/megalabsapi/repository/ClienteRepository.java
  src/main/java/com/megalabsapi/service/CitaService.java
  src/main/resources/data-test.sql
Labels: Backend
