Repository dsanchezchu/megalabs-api, pull requests merged in 2024-10, with the labels that each got.

#35 Feature/histories 1 2 5
  src/main/java/com/megalabsapi/api/CalendarioController.java
  src/main/java/com/megalabsapi/api/ControlCalidadController.java
  src/main/java/com/megalabsapi/api/EntregaMuestraController.java
  src/main/java/com/megalabsapi/dto/EntregaMuestraDTO.java
  src/main/java/com/megalabsapi/dto/EntrevistaDTO.java
  src/main/java/com/megalabsapi/dto/EstudioClinicoDTO.java
  src/main/java/com/megalabsapi/model/entity/Cliente.java
  src/main/java/com/megalabsapi/model/entity/Producto.java
  src/main/java/com/megalabsapi/model/enums/ControlCalidadStatus.java
  src/main/java/com/megalabsapi/repository/ControlCalidadRepository.java
  src/main/java/com/megalabsapi/repository/EntregaMuestraRepository.java
  src/main/java/com/megalabsapi/repository/EntrevistaRepository.java
  src/main/java/com/megalabsapi/service/ControlCalidadService.java
  src/main/java/com/megalabsapi/service/EntregaMuestraService.java
  src/main/java/com/megalabsapi/service/EntrevistaService.java
  src/main/java/com/megalabsapi/service/impl/ControlCalidadServiceImpl.java
  src/main/java/com/megalabsapi/service/impl/EntregaMuestraServiceImpl.java
  src/main/java/com/megalabsapi/service/impl/EntrevistaServiceImpl.java
  src/main/resources/data-test.sql
Labels: sprint 1

#36 feat(backend) Correciones de las relaciones
  src/main/java/com/megalabsapi/model/entity/Control_Calidad.java
  src/main/java/com/megalabsapi/model/entity/Producto.java
  src/main/java/com/megalabsapi/model/entity/Venta.java
  src/main/java/com/megalabsapi/repository/ControlCalidadRepository.java
  src/main/java/com/megalabsapi/service/impl/ControlCalidadServiceImpl.java
  src/main/resources/data-test.sql
Labels: fix

#38 Feature/hu06 historial de visitas
  pom.xml
  src/main/java/com/megalabsapi/api/AdminEntregaMuestraController.java
  src/main/java/com/megalabsapi/config/SwaggerAPIConfig.java
  src/main/java/com/megalabsapi/model/entity/Entrega_Muestra.java
  src/main/java/com/megalabsapi/model/entity/Producto.java
  src/main/java/com/megalabsapi/repository/EntregaMuestraRepository.java
  src/main/java/com/megalabsapi/service/AdminEntregaMuestraService.java
  src/main/java/com/megalabsapi/service/impl/EntregaMuestraServiceImpl.java
  src/main/resources/application.properties
  src/main/resources/data-test.sql
Labels: sprint 1

#42 Feature/story9
  src/main/java/com/megalabsapi/api/ChatbotController.java
  src/main/java/com/megalabsapi/api/MetodoAnaliticoController.java
  src/main/java/com/megalabsapi/api/NoConformidadController.java
  src/main/java/com/megalabsapi/model/entity/Control_Calidad.java
  src/main/java/com/megalabsapi/model/entity/Entrega_Muestra.java
  src/main/java/com/megalabsapi/model/entity/Formula_Desarrollada.java
  src/main/java/com/megalabsapi/model/entity/MetodoAnalitico.java
  src/main/java/com/megalabsapi/model/entity/NoConformidad.java
  src/main/java/com/megalabsapi/model/entity/Pago.java
  src/main/java/com/megalabsapi/repository/FormulaDesarrolladaRepository.java
  src/main/java/com/megalabsapi/repository/MetodoAnaliticoRepository.java
  src/main/java/com/megalabsapi/repository/NoConformidadRepository.java
  src/main/java/com/megalabsapi/repository/ProductoRepository.java
  src/main/java/com/megalabsapi/service/FormulaDesarrolladaService.java
  src/main/java/com/megalabsapi/service/MetodoAnaliticoService.java
  src/main/java/com/megalabsapi/service/NoConformidadService.java
  src/main/java/com/megalabsapi/service/impl/FormulaDesarrolladaServiceImpl.java
  src/main/java/com/megalabsapi/service/impl/MetodoAnaliticoServiceImpl.java
  src/main/java/com/megalabsapi/service/impl/NoConformidadServiceImpl.java
  src/main/resources/data-test.sql
Labels: Backend
